package internal

var JuzgadosMap = map[string]string{
	"AUXILIAR_1":           "aux1",
	"AUXILIAR_2":           "aux2",
	"CIVIL_2":              "civ2",
	"CIVIL_3":              "civ3",
	"CIVIL_4":              "civ4",
	"FAMILIAR_1":           "fam1",
	"FAMILIAR_2":           "fam2",
	"FAMILIAR_3":           "fam3",
	"FAMILIAR_4":           "fam4",
	"FAMILIAR_5":           "fam5",
	"MERCANTIL_1":          "mer1",
	"MERCANTIL_2":          "mer2",
	"MERCANTIL_3":          "mer3",
	"MERCANTIL_4":          "mer4",
	"MERCANTIL_ORAL":       "merOral",
	"SECRETARIA_COLEGIADA": "seccc",
	"SECRETARIA_UNITARIA":  "seccu",
	"CJM_FAMILIAR_1":       "cjmf1",
	"CJM_FAMILIAR_2":       "cjmf2",
	"LABORAL":              "trib1",
}

var CodesMap = map[string]string{
	"aux1":    "Primero Auxiliar",
	"aux2":    "Segundo Auxiliar",
	"civ2":    "Segundo Civil",
	"civ3":    "Tercero Civil",
	"civ4":    "Cuarto Civil",
	"fam1":    "Primero Familiar",
	"fam2":    "Segundo Familiar",
	"fam3":    "Tercero Familiar",
	"fam4":    "Cuarto Familiar",
	"fam5":    "Quinto Familiar",
	"mer1":    "Primero Mercantil",
	"mer2":    "Segundo Mercantil",
	"mer3":    "Tercero Mercantil",
	"mer4":    "Cuarto Mercantil",
	"merOral": "Oral Mercantil",
	"seccc":   "Sala Civil Colegiada",
	"seccu":   "Sala Civil Unitaria",
	"cjmf1":   "Primero Especializado Familiar",
	"cjmf2":   "Segundo Especializado Familiar",
	"trib1":   "Tribunal Laboral",
}
